import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Calc from '../containers/Calc.tsx';

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Calculator</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<script src="math.js" type="text/javascript"></script>
			</Head>

			<main className={styles.main}>
				<Calc />
			</main>
		</div>
	)
}

export default Home
